version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data:/app/data
    depends_on:
      - redis
      - chrome
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    restart: unless-stopped

  worker:
    build: .
    volumes:
      - .:/app
      - ./data:/app/data
    depends_on:
      - redis
      - chrome
    env_file:
      - .env
    command: celery -A worker worker --loglevel=info
    restart: unless-stopped

  beat:
    build: .
    volumes:
      - .:/app
      - ./data:/app/data
    depends_on:
      - redis
      - chrome
    env_file:
      - .env
    command: celery -A worker beat --loglevel=info
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    shm_size: 2g
    restart: unless-stopped

volumes:
  data:
  redis_data:
